### ISSUE TITLE
GSF.Core / DigitalFilter.cs, Filtfilt function does not compile

### ISSUE THREAD

**Issue by ajstadlin** [GridProtectionAlliance/gsf#116]
The last few GSF.Core commits are not compiling for me.  I get the following error:

Error CS1929 'double' does not contain a definition for 'Reverse' and the best extension method overload 'StringExtensions.Reverse(string)' requires a receiver of type 'string'

master branch commit 3d1181abb32833931e4e46d0ec2867d2b97b0a46
Date:   Fri Feb 17 03:33:46 2023 -0500
    Added Filtfilt

//AJ

**Comment by ritchiecarroll** [comment]
Thanks AJ, I will check it - great to hear from you!

**Comment by ajstadlin** [comment]
Thanks RC for this great project!  I can't wait to try working with the .NET 6/7 version!
