### ISSUE TITLE
CSU created database account can't be used for upgrade

### ISSUE THREAD

**Issue by arkrohne** [GridProtectionAlliance/gsf#21]
If you create a database account using the configuration setup utility, and upgrade without making any database changes, you'll get an error on updating users roles. The account created by the configuration setup utility doesn't have permission to make those changes, and there is not a way to specify a different account for the configuration setup utility vs. the application during the upgrade process.

**Comment by StephenCWills** [comment]
Resolved with recent changes to the Configuration Setup Utility.
