### ISSUE TITLE
CSU crashes with an invalid SQL hostname, rather than error message

### ISSUE THREAD

**Issue by arkrohne** [GridProtectionAlliance/gsf#22]
If the CSU can't connect to the SQL host, the CSU will crash, rather than display the connection failed message you get when you hit the 'Test Connection' button.

**Comment by chefsteph9** [comment]
Fixed this issue in:
openPDC
openHistorian
openECA
openMIC
PDQTracker
ProjectAlpha
SIEGate
SubstationSBG

I think that's all the applications that use the CSU.
