### ISSUE TITLE
Feature Request - Windows Performance Counters

### ISSUE THREAD

**Issue by EEParker** [GridProtectionAlliance/gsf#23]
I would be nice if gsf based applications such as SIEGate, openHistorian, openPDC, etc. had a basic set of windows performance counters, such as the statistics from the main page.

This could be used by standard IT monitoring tools that can utilize windows perf counters for alerting and status monitoring.

![image](https://user-images.githubusercontent.com/15874076/26948266-51a17624-4c5b-11e7-9a2a-5bb44cd09985.png)

And perhaps optional statistics per input/output streams with totals. 
![image](https://user-images.githubusercontent.com/15874076/26948331-91d3f6cc-4c5b-11e7-8444-5e38ba4620c5.png)

**Comment by StephenCWills** [comment]
The statistics on the main page are actually all calculated by sampling standard Windows performance counters. You should already have the ability to monitor those using the standard IT monitoring tools you've described.

**Comment by EEParker** [comment]
OK, I do think we can get those basic perf counters. 

What do you think about performance counters for the run time statistics for I/O streams? My idea was to have a custom performance counter category for GSF and the counter could have instances for each application+stream. Here is an example.

![image](https://user-images.githubusercontent.com/15874076/27233124-11e2fdc2-527e-11e7-95d4-ffcdec128c7c.png)

**Comment by ritchiecarroll** [comment]
I think these could be added fairly easily...
