### ISSUE TITLE
Service fails to start if StatusLog.txt is read-only

### ISSUE THREAD

**Issue by arkrohne** [GridProtectionAlliance/gsf#24]
If a service is not able to write to StatusLog.txt, the service will fail to start, silently, with no error in the event log or in ErrorLog.txt

**Comment by chefsteph9** [comment]
In my testing with the latest release of openHistorian, I found that the service does actually produce an error in the event log if StatusLog.txt is read-only.

If you are still able to reproduce this issue, I will need more information about your system to be able to reproduce the issue myself.
