### ISSUE TITLE
It does not work with the server IP addresses

### ISSUE THREAD

**Issue by jenokizm** [GridProtectionAlliance/gsf#41]
example 
` s_client = new TcpClient("Server=localhost:8888"); //work it`
but
` s_client = new TcpClient("Server=127.0.0.1:8888"); //not work!`
Also with other addresses on different computers. What is the reason?

**Comment by ritchiecarroll** [comment]
Does this work:
`s_client = new TcpClient("Server=127.0.0.1:8888; interface=0.0.0.0");`

Could be an IPv6 issue.

**Comment by jenokizm** [comment]
Thanks now it works
