### ISSUE TITLE
SendDataComplete how bytes are sent?

### ISSUE THREAD

**Issue by jenokizm** [GridProtectionAlliance/gsf#45]
Hi, im using **SendDataComplete** event in TcpClient and **SendClientDataComplete** in TcpServer.
How in both cases to find out how many bytes sent?

**Comment by ritchiecarroll** [comment]
For send data complete in TcpClient, you will get the data buffer in argument 1 and the count in argument 2, see below:

https://github.com/GridProtectionAlliance/gsf/blob/master/Source/Libraries/GSF.Communication/ClientBase.cs#L181 

/// <summary>
/// Occurs when data received from the   server has been processed and is ready for consumption.
/// </summary>
/// <remarks>
/// <see cref="EventArgs{T1,T2}.Argument1"/> is a new   buffer containing post-processed data received from the server starting at   index zero.<br/>
/// <see cref="EventArgs{T1,T2}.Argument2"/> is the   number of post-processed bytes received in the buffer from the server.
/// </remarks>
[Category("Data"),
Description("Occurs when data received   from the server has been processed and is ready for consumption.")]
public event EventHandler<EventArgs<byte[], int>> ReceiveDataComplete;

For send data _client_ complete in TcpServer, first arg is a Guid (representing the unique client connection ID) – then arg2 is buffer and arg3 is count, see:

https://github.com/GridProtectionAlliance/gsf/blob/master/Source/Libraries/GSF.Communication/ServerBase.cs#L203

**Comment by ritchiecarroll** [comment]
Actually, just noticed you said "Send" not "Receive", sorry - in that case:

**Comment by jenokizm** [comment]
Someone from us delicately buggy. But I asked about the events of sending and not receiving. Sending events do not have such agrunments as receiving, this is the problem!

**Comment by ritchiecarroll** [comment]
So sorry - my mistake. I am guessing that since these notifications were just indications, i.e., a confirmation, of data that the user had already sent (and hence had access to), that the original buffer was not included in the notification. Do you have a use case where this would be useful?

**Comment by jenokizm** [comment]
I need this for a reason. I have a p2p program in each of which the client and the server are running. I want to collect from the sending and receiving events the number of bytes and then show traffic on the graph in real time.
![image](https://user-images.githubusercontent.com/11296510/45233819-a5dbe100-b2dc-11e8-9f42-6059103d60ee.png)

**Comment by StephenCWills** [comment]
FYI, something like this ought to work.

```
        private static void Server_SendClientDataComplete(object sender, EventArgs<Guid> e)
        {
            TcpServer server = sender as TcpServer;
            Guid clientID = e.Argument;
            
            if (server.TryGetClient(clientID, out TransportProvider<Socket> client))
            {
                int bytesSent = client.Statistics.LastBytesSent;
                // Got bytes sent!
            }
        }
```
