### ISSUE TITLE
.NET Core support

### ISSUE THREAD

**Issue by alexeyfv** [GridProtectionAlliance/gsf#58]
Hello.

Is it possible to use GSF libraries (for example COMTRADE) for cross-platform applications? I've checked Gemstone Libraries but there isn't COMTRADE library. Are you planning to port GSF libraries to .NET Core platform? It would be great.

**Comment by clackner-gpa** [comment]
Hi Fedorov,
We are planning on moving the COMTRADE GSF library to .Net Core and add it to the Gemstone Libraries in the near future.

**Comment by mmiecz** [comment]
I've just stumbled on this issue, and I'm interested in this as well.
What is the current status of .NET Core support for COMTRADE?
Thanks!

**Comment by ritchiecarroll** [comment]
We are about to check-in an update to the existing .NET Framework COMTRADE code for support of CFF file format (and other feature updates).

As soon as this is complete (and tested), we will migrate it over to the Gemstone libraries that are based on .NET 5.0 (Core)

**Comment by blingdaag** [comment]
Hello, 

We are currently working on a conversion and would like to know if you have any updates you can please share as it relates to your migration to .NET Core (.NET 5 or potentially 6?).

Thanks and Regards,
-jermaine

**Comment by ritchiecarroll** [comment]
@blingdaag - does this relate to GSF in general or COMTRADE?

**Comment by gitkrasty** [comment]
In my case it is related to COMTRADE specifically. And the decision will have to be taken in a month or two in our team for at least  next 3 years, as it is for a funded project.

**Comment by ritchiecarroll** [comment]
Gotcha - this conversion was supposed to happen over the holidays already - so I'll see what I can do about getting it migrated ASAP.

Thanks,
Ritchie

**Comment by josef-stromsky** [comment]
Hello,
Any updates in this matter? Is there any estimate, when it could be available? It would be of a great help for us to know the possible date approximately at least.
Thanks a lot.

**Comment by ritchiecarroll** [comment]
This is completed: 
* https://github.com/gemstone/comtrade

Docs:
* https://gemstone.github.io/comtrade/

*NuGet:
https://www.nuget.org/packages/Gemstone.COMTRADE

**Comment by ritchiecarroll** [comment]
Closing this issue since this has been completed (https://gemstone.github.io/comtrade/)
