### ISSUE TITLE
ExpressionEvaluator license?

### ISSUE THREAD

**Issue by dwiley007** [GridProtectionAlliance/gsf#59]
Hello,

One of the dependencies is ExpressionEvaluator, however the version of the package used (v2.0.4) does not specify a license on NuGet. Also it seems this project has been taken over by another company, since it was included in GSF library. Can you please clarify the license for the package?

Thanks.

**Comment by StephenCWills** [comment]
If you do some searching, it seems there is a CodePlex archive for v1.0.4 of the Expression Evaluator with the MIT license. It wouldn't be too far-fetched to assume that the last freely available version was also licensed under MIT, although I haven't been able to track down the source code to verify. I would recommend contacting the owner of the NuGet package for further clarification.
