### ISSUE TITLE
Separate connection errors from errorlog

### ISSUE THREAD

**Issue by arkrohne** [GridProtectionAlliance/gsf#6]
The ErrorLog.txt log is often filled with connection issues of failing or intermittent devices. Separating those out into a second connection error log would simplify finding configuration or operational errors.

**Comment by ritchiecarroll** [comment]
How about a flag to optionally log these at all?

**Comment by arkrohne** [comment]
That may be the simplest solution. Sometimes it's useful to see if an error occurred near a connect/disconnect event, but you often don't need that data for the whole time.

**Comment by rmc00** [comment]
@ritchiecarroll Would this be a flag on the adapter level or something more global? Seems like it could be implemented in InputAdapterBase and OutputAdapterBase on the reconnect timer logic.

**Comment by ritchiecarroll** [comment]
@rmc00 that might work, but I think to reduce noise in this case simply implementing some error filter right inside the PhasorMeasurementMapper adapter would suffice. Do you want to take a stab at it?

**Comment by rmc00** [comment]
Yeah, I thought I might give it a shot.

**Comment by ritchiecarroll** [comment]
Feature completed.
