### ISSUE TITLE
Error getting nuget packages: "The repository primary signature validity period has expired"

### ISSUE THREAD

**Issue by hrvojej** [GridProtectionAlliance/gsf#88]
Hi,

I'm getting error while trying to retrieve nuget packages for GFS.Core library in Visual Studio.
Any idea how to get around this?

Cheers!

**Comment by ritchiecarroll** [comment]
Well - that's not good. We'll check it out...

**Comment by ritchiecarroll** [comment]
How about now? I think I must have been using the wrong API key, I just re-regenerated and the package upload seemed to work.

**Comment by ritchiecarroll** [comment]
I think we're good here now - so I am going to close this. Feel free to re-open if you feel this hasn't been resolved.
