### ISSUE TITLE
ConcentratorBase all the measurements end up in the OnDiscardingMeasurements 

### ISSUE THREAD

**Issue by Mozart100** [GridProtectionAlliance/gsf#96]
Hi,

Our class DatabaseConcentrator inherits from ConcentratorBase , when we are calling SortMeasurements we pass measurements with timestamps of not of UTC.NOW, which ends up in OnDiscardingMeasurements.

Is there a way to configure or do anything which allows DatabaseConcentrator to accept the measurements in their original twisted DateTime format without them being filtered(OnDiscardingMeasurements )???

**Comment by ritchiecarroll** [comment]
This has to do with real-time settings of concentrator, e.g., lead-time / lag-time - also, for very high-volume data you need to adjust the sorting strategy to be based on arrival time.

I don't think this this is an issue with the concentrator, so I am going to close this as an "issue". I suggest if you need assistance in usage of the `ConcentratorBase` class, you request help from our discussions board:

https://discussions.gridprotectionalliance.org/

Thanks!
Ritchie
